schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - windows-new-dir-hierarchy
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - windows-new-dir-hierarchy

jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2022
    image_readme_name: Windows2022-Readme.md
    image_template_name: windows-2022.json
